### ISSUE TITLE
Better speaking rate estimation with long silence removal

### ISSUE THREAD

**Issue by gizemt** [huggingface/dataspeech#6]
Is anyone working on “Better speaking rate estimation with long silence removal”? 

I’m playing with a potential solution using Brouhaha-vad (same as [here](https://github.com/huggingface/dataspeech/blob/b17fed7519146239d128ca016516b1260c68787a/dataspeech/gpu_enrichments/snr_and_reverb.py#L12)) and then computing speech rate as #phonemes / speech duration. If that approach works for you, I can test the code and create a PR. If there’s another approach in mind, I’d be happy to help with that as well.

**Comment by ylacombe** [comment]
Hey @gizemt, as far as I know, nobody is working on this yet! thanks for opening this issue !
This approach seems the most reasonable to me, feel free to test it and open a PR! also, it'd be great to have examples on how to make this work and how efficient it is, if you can!

BTW, do you think VAD with Brouhaha is more efficient than using other VAD libraries (such as pyannote)?

**Comment by ylacombe** [comment]
Done in #24 !
